# -*- coding: utf-8 -*-
"""FYP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uozN64MW8RTL0CZtFNney22ugc0dz7N
"""

CONTENT_WEIGHT = 1e4
STYLE_WEIGHT = 1e-2
TV_WEIGHT = 30
NUM_STEPS = 500
LEARNING_RATE = 0.02

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from dataclasses import dataclass
from google.colab import files

# =========================
# Configuration
# =========================
@dataclass
class NSTConfig:
    max_dim: int = 512
    steps: int = 250
    learning_rate: float = 0.02

    content_weight: float = 1e4
    style_weight: float = 1e-2
    tv_weight: float = 30.0  # total variation regularisation

    content_layers: tuple = ("block5_conv2",)
    style_layers: tuple = (
        "block1_conv1",
        "block2_conv1",
        "block3_conv1",
        "block4_conv1",
        "block5_conv1",
    )

CFG = NSTConfig()

# =========================
# Image utilities
# =========================
def load_and_resize_image(path: str, max_dim: int) -> tf.Tensor:
    """Load an image and resize preserving aspect ratio. Returns float tensor [1,H,W,3]."""
    img = Image.open(path).convert("RGB")
    w, h = img.size
    scale = max_dim / max(w, h)
    new_w, new_h = int(w * scale), int(h * scale)
    img = img.resize((new_w, new_h))

    arr = np.array(img).astype(np.float32)
    return tf.convert_to_tensor(arr)[tf.newaxis, ...]

def show_image(t: tf.Tensor, title: str = "") -> None:
    img = tf.squeeze(t, axis=0)
    img = tf.clip_by_value(img, 0.0, 255.0)
    img = tf.cast(img, tf.uint8).numpy()

    plt.figure(figsize=(6, 6))
    if title:
        plt.title(title)
    plt.imshow(img)
    plt.axis("off")
    plt.show()

def save_tensor_as_image(t: tf.Tensor, filename: str) -> None:
    img = tf.squeeze(t, axis=0)
    img = tf.clip_by_value(img, 0.0, 255.0)
    img = tf.cast(img, tf.uint8).numpy()
    Image.fromarray(img).save(filename)

# =========================
# Model utilities
# =========================
def build_vgg_feature_extractor(layer_names):
    """Create a frozen VGG19 model that outputs selected intermediate layer activations."""
    vgg = tf.keras.applications.VGG19(include_top=False, weights="imagenet")
    vgg.trainable = False
    outputs = [vgg.get_layer(n).output for n in layer_names]
    return tf.keras.Model(inputs=vgg.input, outputs=outputs)

def gram_matrix(feature_maps: tf.Tensor) -> tf.Tensor:
    """Compute Gram matrix for style representation. feature_maps: [1,H,W,C] -> [1,C,C]."""
    result = tf.linalg.einsum("bijc,bijd->bcd", feature_maps, feature_maps)
    h = tf.shape(feature_maps)[1]
    w = tf.shape(feature_maps)[2]
    num_locations = tf.cast(h * w, tf.float32)
    return result / num_locations

class NSTFeatureModel(tf.keras.Model):
    """Extract content and style features from a frozen VGG network."""
    def __init__(self, style_layers, content_layers):
        super().__init__()
        self.style_layers = list(style_layers)
        self.content_layers = list(content_layers)
        self.all_layers = self.style_layers + self.content_layers

        self.vgg = build_vgg_feature_extractor(self.all_layers)
        self.vgg.trainable = False
        self.num_style = len(self.style_layers)

    def call(self, x: tf.Tensor):
        x = tf.keras.applications.vgg19.preprocess_input(x)
        outputs = self.vgg(x)

        style_out = outputs[:self.num_style]
        content_out = outputs[self.num_style:]

        style_features = {n: gram_matrix(v) for n, v in zip(self.style_layers, style_out)}
        content_features = {n: v for n, v in zip(self.content_layers, content_out)}
        return style_features, content_features

# =========================
# Loss functions
# =========================
def compute_content_loss(gen_content, target_content) -> tf.Tensor:
    losses = [tf.reduce_mean((gen_content[k] - target_content[k]) ** 2) for k in target_content.keys()]
    return tf.add_n(losses)

def compute_style_loss(gen_style, target_style) -> tf.Tensor:
    losses = [tf.reduce_mean((gen_style[k] - target_style[k]) ** 2) for k in target_style.keys()]
    return tf.add_n(losses)

def total_variation_regulariser(image: tf.Tensor) -> tf.Tensor:
    return tf.reduce_sum(tf.image.total_variation(image))

def total_loss(image, gen_style, gen_content, style_target, content_target, cfg: NSTConfig) -> tf.Tensor:
    style_l = compute_style_loss(gen_style, style_target) / len(cfg.style_layers)
    content_l = compute_content_loss(gen_content, content_target) / len(cfg.content_layers)
    tv_l = total_variation_regulariser(image)

    return (cfg.style_weight * style_l) + (cfg.content_weight * content_l) + (cfg.tv_weight * tv_l)

# =========================
# Optimisation step (IMPORTANT FIX)
# - Do NOT pass cfg into tf.function
# - Use global CFG inside to avoid TraceType error
# =========================
@tf.function
def optimisation_step(image: tf.Variable,
                      model: NSTFeatureModel,
                      style_target,
                      content_target,
                      optimiser):
    with tf.GradientTape() as tape:
        gen_style, gen_content = model(image)
        loss = total_loss(image, gen_style, gen_content, style_target, content_target, CFG)

    grads = tape.gradient(loss, image)
    optimiser.apply_gradients([(grads, image)])
    image.assign(tf.clip_by_value(image, 0.0, 255.0))
    return loss

# =========================
# Run the prototype
# =========================
print("Upload TWO images: (1) content image, (2) style image")
uploaded = files.upload()
uploaded_files = list(uploaded.keys())

if len(uploaded_files) < 2:
    raise ValueError("Please upload TWO images (content and style).")

content_path = uploaded_files[0]
style_path = uploaded_files[1]

content_img = load_and_resize_image(content_path, CFG.max_dim)
style_img = load_and_resize_image(style_path, CFG.max_dim)

show_image(content_img, "Content Image")
show_image(style_img, "Style Image")

# Build feature model and targets
feature_model = NSTFeatureModel(CFG.style_layers, CFG.content_layers)
style_target, _ = feature_model(style_img)
_, content_target = feature_model(content_img)

# Initialise generated image from content (stable)
image = tf.Variable(content_img)

optimiser = tf.keras.optimizers.Adam(learning_rate=CFG.learning_rate)

for step in range(1, CFG.steps + 1):
    loss_val = optimisation_step(image, feature_model, style_target, content_target, optimiser)
    if step % 50 == 0:
        tf.print("Step", step, "Loss", loss_val)

show_image(image, "Stylised Output")

out_name = "stylised_output.png"
save_tensor_as_image(image, out_name)
print("Saved:", out_name)
files.download(out_name)